version: "3.7"

services:
  postgres_db:
    container_name: garbage
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garbage
    restart: unless-stopped